#!/usr/bin/env bash
set -e

function handlePullRequest {
    npm run build
    npm test
}

case $1 in
    "handle-pull-request")
        handlePullRequest
    ;;
    "handle-merge-to-official-fork")
        handlePullRequest
        npm publish
    ;;
    *)
        echo "Usage:"
        echo ""
        echo "devops/pipeline handle-pull-request"
        echo "devops/pipeline handle-merge-to-official-fork"
        echo ""
        exit 1
    ;;
esac